-- Change primary keys from UUID to SMALLINT for industry_id, industry_role_id, and license_id

-- Step 1: Drop all foreign key constraints that reference these tables
ALTER TABLE maker_preference DROP CONSTRAINT IF EXISTS maker_preference_industry_id_fkey;
ALTER TABLE maker_preference DROP CONSTRAINT IF EXISTS maker_preference_industry_role_id_fkey;
ALTER TABLE employer DROP CONSTRAINT IF EXISTS employer_industry_id_fkey;
ALTER TABLE industry_role DROP CONSTRAINT IF EXISTS industry_role_industry_id_fkey;
ALTER TABLE maker_license DROP CONSTRAINT IF EXISTS maker_license_license_id_fkey;
ALTER TABLE job_license DROP CONSTRAINT IF EXISTS job_license_license_id_fkey;

-- Step 2: Drop and recreate the industry table with SMALLINT primary key
DROP TABLE IF EXISTS industry CASCADE;
CREATE TABLE industry (
    industry_id SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE
);

-- Step 3: Drop and recreate the industry_role table with SMALLINT primary key
DROP TABLE IF EXISTS industry_role CASCADE;
CREATE TABLE industry_role (
    industry_role_id SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    industry_id SMALLINT NOT NULL REFERENCES industry(industry_id) ON DELETE CASCADE,
    role TEXT NOT NULL
);

-- Step 4: Drop and recreate the license table with SMALLINT primary key
DROP TABLE IF EXISTS license CASCADE;
CREATE TABLE license (
    license_id SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE
);

-- Step 5: Update foreign key columns in referencing tables to SMALLINT
ALTER TABLE maker_preference ALTER COLUMN industry_id TYPE SMALLINT;
ALTER TABLE maker_preference ALTER COLUMN industry_role_id TYPE SMALLINT;
ALTER TABLE employer ALTER COLUMN industry_id TYPE SMALLINT;
ALTER TABLE maker_license ALTER COLUMN license_id TYPE SMALLINT;
ALTER TABLE job_license ALTER COLUMN license_id TYPE SMALLINT;

-- Step 6: Re-add foreign key constraints
ALTER TABLE maker_preference ADD CONSTRAINT maker_preference_industry_id_fkey 
    FOREIGN KEY (industry_id) REFERENCES industry(industry_id);
ALTER TABLE maker_preference ADD CONSTRAINT maker_preference_industry_role_id_fkey 
    FOREIGN KEY (industry_role_id) REFERENCES industry_role(industry_role_id);
ALTER TABLE employer ADD CONSTRAINT employer_industry_id_fkey 
    FOREIGN KEY (industry_id) REFERENCES industry(industry_id);
ALTER TABLE industry_role ADD CONSTRAINT industry_role_industry_id_fkey 
    FOREIGN KEY (industry_id) REFERENCES industry(industry_id) ON DELETE CASCADE;
ALTER TABLE maker_license ADD CONSTRAINT maker_license_license_id_fkey 
    FOREIGN KEY (license_id) REFERENCES license(license_id) ON DELETE CASCADE;
ALTER TABLE job_license ADD CONSTRAINT job_license_license_id_fkey 
    FOREIGN KEY (license_id) REFERENCES license(license_id) ON DELETE CASCADE;

-- Step 7: Re-insert predefined industry data
INSERT INTO industry (name) VALUES
    ('Healthcare & Medical (Critical Sectors)'),
    ('Tourism & Hospitality'),
    ('Construction'),
    ('Natural Disaster Recovery'),
    ('Mining'),
    ('Plant & Animal Cultivation'),
    ('Tree Farming & Felling'),
    ('Fishing & Pearling');

-- Step 8: Re-insert industry roles
INSERT INTO industry_role (industry_id, role) VALUES
    -- Plant & Animal Cultivation roles (industry_id = 6)
    (6, 'Fruit Picker'),
    (6, 'Packer'),
    (6, 'Dairy Worker'),
    (6, 'Livestock Worker'),
    (6, 'Horse Breeder'),
    (6, 'Reforestation Worker'),
    
    -- Fishing & Pearling roles (industry_id = 8)
    (8, 'Deckhand'),
    (8, 'Aquaculture Worker'),
    (8, 'Pearl Diver'),
    
    -- Tree Farming & Felling roles (industry_id = 7)
    (7, 'Tree Planter'),
    (7, 'Logger'),
    (7, 'Timber Transport Worker'),
    
    -- Mining roles (industry_id = 5)
    (5, 'Driller'),
    (5, 'Truck Driver'),
    (5, 'Quarry Operator'),
    (5, 'Exploration Worker'),
    
    -- Construction roles (industry_id = 3)
    (3, 'Labourer'),
    (3, 'Painter'),
    (3, 'Scaffolder'),
    (3, 'Site Cleaner'),
    
    -- Tourism & Hospitality roles (industry_id = 2)
    (2, 'Chef'),
    (2, 'Bartender'),
    (2, 'Waitstaff'),
    (2, 'Housekeeper'),
    (2, 'Tour Guide'),
    
    -- Natural Disaster Recovery roles (industry_id = 4)
    (4, 'Clean-up Crew'),
    (4, 'Rebuilder'),
    (4, 'Wildlife Carer'),
    
    -- Healthcare & Medical roles (industry_id = 1)
    (1, 'Nurse'),
    (1, 'Aged Care Worker'),
    (1, 'Disability Support'),
    (1, 'Childcare Worker'),
    (1, 'Cleaner');

-- Step 9: Re-insert predefined license data
INSERT INTO license (name) VALUES
    ('White Card (Construction)'),
    ('RSA (Responsible Service of Alcohol)'),
    ('RSG (Responsible Service of Gaming)'),
    ('Food Safety Supervisor'),
    ('First Aid Certificate'),
    ('Driver''s License'),
    ('Forklift License'),
    ('Working at Heights'),
    ('Manual Handling'),
    ('Chemical Handling'),
    ('Other');

-- Step 10: Re-enable RLS and recreate policies for the recreated tables
ALTER TABLE industry ENABLE ROW LEVEL SECURITY;
ALTER TABLE industry_role ENABLE ROW LEVEL SECURITY;
ALTER TABLE license ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read industries" ON industry FOR SELECT USING (true);
CREATE POLICY "Public can read industry roles" ON industry_role FOR SELECT USING (true);
CREATE POLICY "Public can read licenses" ON license FOR SELECT USING (true);

-- Step 11: Recreate indexes
CREATE INDEX idx_industry_role_industry ON industry_role(industry_id);