// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqdpmzqawidznafiwzre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xZHBtenFhd2lkem5hZml3enJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMDEwMDksImV4cCI6MjA3Mjc3NzAwOX0.HIhdY9vZ2KyfT-8EayBc9UP3s5wnZgAzGC47C4HKLSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});